#!/bin/bash

export RELEASE=$RELEASE
export VERSION=$VERSION

if [ "${RELEASE}" = "YES" ]; then
   export FORCE_RETROARCH_BUILD=YES
else
   export FORCE_RETROARCH_BUILD=NO
fi

echo RELEASE=$RELEASE
echo VERSION=$VERSION
echo FORCE_RETROARCH_BUILD=$FORCE_RETROARCH_BUILD


if [ ! -f /home/buildbot/tmp/buildbot.lock ]; then
   touch /home/buildbot/tmp/buildbot.lock
   echo "buildbot not running"
else
   echo "buildbot already running"
   exit
fi

# Console targets first, usually smaller
/home/buildbot/buildbot-x64
/home/buildbot/buildbot-x86

rm /home/buildbot/tmp/buildbot.lock
rm /home/buildbot/tmp/built*

