#!/bin/sh
export BASEDIR=/home/buildbot
source $BASEDIR/scripts/release

echo BASEDIR=$BASEDIR
echo RELEASE=$RELEASE
echo VERSION=$VERSION

cd $BASEDIR/scripts
git pull
cd $BASEDIR

screen -dmS buildbot $BASEDIR/scripts/buildbot-master
screen -list
