#!/bin/bash

LOGDATE=`date +%Y-%m-%d`
BUILDBOT=vaporeon_win
if [ "${RELEASE}" == "YES" ]; then
   DEST=/home/buildbot/www/stable/$VERSION/windows/x86_64
else
   DEST=/home/buildbot/www/nightly/windows/x86_64
fi

LOGDEST=/home/buildbot/www/log/
echo $LOGDATE $BUILDBOT
TMPDIR=/home/buildbot/tmp/

mkdir -p $DEST
mkdir -p $LOGDEST


mkdir -p $TMPDIR/log/$BUILDBOT/${LOGDATE}
echo Buildbot Summary >> $TMPDIR/log/${BUILDBOT}/${LOGDATE}.log
echo ========================================== >> $TMPDIR/log/${BUILDBOT}/${LOGDATE}.log


cd buildbot
WORKDIR=$PWD
LOGURL="https://floating.muncher.se/bot/connect/buildbot.php"
SIG="ekkC3Zhw2LlPKpvqOxPNlrHEh27dCzL6gTIVbF36fSUBZBEOZGkh4gaF9LhpqRpX"

### windows x86_64 ###

# prepare build environment
BOT=$PWD/windows_x64
cd $BOT
git pull

rm -rf packages
#build cores
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=2 ./libretro-buildbot-recipe.sh recipes/windows/retroarch-windows-x64_seh
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=2 ./libretro-buildbot-recipe.sh recipes/windows/cores-windows-x64_seh-generic
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=2 ./libretro-buildbot-recipe.sh recipes/windows/cores-windows-x64_seh-cross
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=2 ./libretro-buildbot-recipe.sh recipes/windows/cores-windows-x64_sjlj-generic

# create packages and cleanup
if [ ! -f $TMPDIR/built-frontend -a ! -f $TMPDIR/built-cores ]; then
    echo "Nothing to do here!"
else
        echo BUILDBOT TASK: packaging cores
        CORE_DIR=$PWD/packages/$(date +%F)_cores
	RA_DIR=$PWD/packages/$(date +%F)_retroarch

        rm -rfv $CORE_DIR
        rm -rfv $RA_DIR

        mkdir -p $CORE_DIR
	mkdir -p $RA_DIR
        mkdir -p $DEST

        cd $CORE_DIR
        mkdir ../latest

        find ../../dist/win_x64 -name '*.dll' -mmin -2160 -exec cp -v '{}' . \;

        find . -type f -name '*.dll' -exec zip -j '{}'.zip '{}' \;
        find . -type f -name '*.dll' -exec rm -v '{}' \;
        cp -v *.zip ../latest/

        cd $RA_DIR
        cp -rv ../../retroarch/windows/*.exe .
	7z a -mx9 $DEST/$(date +%F)_RetroArch.7z .


	cd ..
	rm -rfv $RA_DIR
        mkdir -p $RA_DIR

        cd $RA_DIR
        cp -rv ../../retroarch/windows/* .
        wget http://bot.libretro.com/nightly/windows/x86_64/redist-x86_64.7z
        7z x redist-x86_64.7z
        rm redist-x86_64.7z

	wget http://bot.libretro.com/assets/frontend/bundle.zip
	unzip bundle.zip
	rm bundle.zip

	7z a -mx9 $DEST/RetroArch.7z .

        cd ..
        rm -rfv $RA_DIR

        cd $BOT
        cp -rfv packages/* $DEST
        cp -rfv $TMPDIR/log/* $LOGDEST



fi

## end ###
rm $TMPDIR/built-cores $TMPDIR/built-frontend

