#!/bin/bash

LOGDATE=`date +%Y-%m-%d`
BUILDBOT=linux-bot
if [ "${RELEASE}" == "YES" ]; then
   DEST=$BASEDIR/www/stable/$VERSION/playstation/vita/
else
   DEST=$BASEDIR/www/nightly/playstation/vita/
fi

LOGDEST=$BASEDIR/www/log/
echo $LOGDATE $BUILDBOT
TMPDIR=$BASEDIR/.tmp/

mkdir -p $TMPDIR/log/$BUILDBOT/${LOGDATE}
echo Buildbot Summary

cd $BASEDIR
cd buildbot
WORKDIR=$PWD

### vita ###

# prepare build environment
BOT=$PWD/vita
cd $BOT
git pull

rm -rf packages
#build cores
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=2 ./libretro-buildbot-recipe.sh recipes/playstation/vita

# create packages and cleanup
if [ ! -f $TMPDIR/built-frontend -a ! -f $TMPDIR/built-cores ]; then
    echo "Nothing to do here!"
else
    echo BUILDBOT TASK: packaging cores
    CORE_DIR=$PWD/retroarch/pkg/vita
    mkdir -p $DEST
    cd $CORE_DIR
    ls -la

    if [ "${RELEASE}" == "YES" ]; then
      7z a -mx9 $DEST/RetroArch.7z
    else
	   7z a -mx9 $DEST/$(date +%F)_RetroArch.7z
    fi
fi

## end ###
rm $TMPDIR/built-cores $TMPDIR/built-frontend
