#!/bin/bash

LOGDATE=`date +%Y-%m-%d`
BUILDBOT=linux-bot
DEST=$BASEDIR/www/assets/frontend
LOGDEST=$BASEDIR/www/log/
echo $LOGDATE $BUILDBOT
TMPDIR=$BASEDIR/.tmp/

mkdir -p $TMPDIR/log/$BUILDBOT/${LOGDATE}
mkdir -p $DEST
echo Buildbot Summary | tee -a  $TMPDIR/log/${BUILDBOT}/${LOGDATE}.log

cd $BASEDIR
cd buildbot
WORKDIR=$PWD

### assets ###

# prepare build environment
BOT=$PWD/assets
cd $BOT

git clone https://github.com/libretro/retroarch-joypad-autoconfig.git autoconf
git clone https://github.com/libretro/libretro-super.git super
git clone https://github.com/libretro/common-shaders shaders_cg
git clone https://github.com/libretro/retroarch-assets assets
git clone https://github.com/libretro/common-overlays.git overlays
git clone https://github.com/libretro/libretro-database.git database

cd autoconf
git pull
git archive --format zip --output $DEST/autoconf.zip master
cd $BOT

cd super
git pull
cd dist/info
zip -j $DEST/info.zip *.info
mkdir $DEST/info
cp *.info $DEST/info
cd $BOT

cd shaders_cg
git pull
git archive --format zip --output $DEST/shaders_cg.zip master
cd $BOT

cd assets
git pull
git archive --format zip --output $DEST/assets.zip master
cd $BOT

cd overlays
git pull
git archive --format zip --output $DEST/overlays.zip master
cd $BOT

cd database
git pull
cd $BOT

cd database/cht
zip -r $DEST/cheats.zip *
cd $BOT
cd database/cursors
zip -r $DEST/database-cursors.zip *
cd $BOT
cd database/rdb
zip -r $DEST/database-rdb.zip *
cd $BOT

cp -rfv  $BASEDIR/buildbot/android/retroarch/media/shaders_glsl $TMPDIR
cd $TMPDIR/shaders_glsl/
rm -rfv .git
git clone https://github.com/hizzlekizzle/glsl-shaders hunterk
cd hunterk
rm -rfv .git
cd ..
cp -rfv hunterk/* .
rm -rfv hunterk
cd $TMPDIR/shaders_glsl
zip -r $DEST/shaders_glsl.zip *
cd $BOT

rm -rfv bundle
mkdir -p bundle/assets
cd bundle/assets
unzip $DEST/assets.zip
cd $BOT
mkdir -p bundle/info
cd bundle/info
unzip $DEST/info.zip
cd $BOT
mkdir -p bundle/autoconf
cd bundle/autoconf
unzip $DEST/autoconf.zip
cd $BOT
mkdir -p bundle/database/rdb
cd bundle/database/rdb
unzip $DEST/database-rdb.zip
cd $BOT
mkdir -p bundle/database/cursors
cd bundle/database/cursors
unzip $DEST/database-cursors.zip
cd $BOT
mkdir -p bundle/overlays
cd bundle/overlays
unzip $DEST/overlays.zip.zip
cd $BOT
mkdir -p bundle/shaders/shaders_glsl
cd bundle/shaders/shaders_glsl
unzip $DEST/shaders_glsl.zip
cd $BOT
mkdir -p bundle/shaders/shaders_cg
cd bundle/shaders/shaders_cg
unzip $DEST/shaders_cg.zip
cd $BOT

cd bundle
zip -r $DEST/bundle.zip *

cd $BOT
rm -rf $TMPDIR/shaders_glsl
## end ###

