#!/bin/bash

LOGDATE=`date +%Y-%m-%d`
BUILDBOT=linux-bot
if [ "${RELEASE}" == "YES" ]; then
   DEST=$BASEDIR/www/stable/$VERSION/nintendo/ngc/
else
   DEST=$BASEDIR/www/nightly/nintendo/ngc/
fi

LOGDEST=$BASEDIR/www/log/
echo $LOGDATE $BUILDBOT
TMPDIR=$BASEDIR/.tmp/

mkdir -p $TMPDIR/log/$BUILDBOT/${LOGDATE}
echo Buildbot Summary | tee -a  $TMPDIR/log/${BUILDBOT}/${LOGDATE}.log

cd $BASEDIR
cd buildbot
WORKDIR=$PWD

### ngc ###

# prepare build environment
BOT=$PWD/ngc
cd $BOT
git pull

rm -rf packages
#build cores
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=6 ./libretro-buildbot-recipe.sh recipes/nintendo/gamecube

# create packages and cleanup
if [ ! -f $TMPDIR/built-frontend -a ! -f $TMPDIR/built-cores ]; then
    echo "Nothing to do here!"
else
	echo BUILDBOT TASK: packaging cores
	CORE_DIR=$PWD/retroarch/pkg/ngc
	mkdir -p $DEST

	cd $CORE_DIR
   if [ "${RELEASE}" == "YES" ]; then
      7z a -mx9 $DEST/RetroArch.7z
   else
	   7z a -mx9 $DEST/$(date +%F)_RetroArch.7z
   fi

fi
## end ###
rm $TMPDIR/built-cores $TMPDIR/built-frontend
