#!/bin/sh
export BASEDIR=/Users/buildbot
source $BASEDIR/release

echo BASEDIR=$BASEDIR
echo RELEASE=$RELEASE
echo VERSION=$VERSION

cd $BASEDIR/scripts
git pull
cd $BASEDIR

$BASEDIR/scripts/buildbot-master-osx
