#!/bin/bash

LOGDATE=`date +%Y-%m-%d`
BUILDBOT=osx-bot
DEST=$BASEDIR/www/nightly/blackberry/
LOGDEST=$BASEDIR/www/log/
echo $LOGDATE $BUILDBOT
TMPDIR=$BASEDIR/.tmp/

mkdir -p $TMPDIR/log/$BUILDBOT/${LOGDATE}
echo Buildbot Summary | tee -a  $TMPDIR/log/${BUILDBOT}/${LOGDATE}.log

cd $BASEDIR
cd buildbot
WORKDIR=$PWD

### blackberry ###

# prepare build environment
BOT=$PWD/blackberry
cd $BOT
git pull
source $BASEDIR/tools/blackberry/blackberry-ndk/bbndk-env_10_3_1_995.sh
echo $PATH

rm -rf packages
#build cores
JOBS=6 TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT ./libretro-buildbot-recipe.sh recipes/blackberry/cores-qnx-generic

# create packages and cleanup
if [ ! -f $TMPDIR/built-frontend -a ! -f $TMPDIR/built-cores ]; then
    echo "Nothing to do here!"
else
        echo BUILDBOT TASK: packaging cores
        CORE_DIR=$PWD/packages/$(date +%F)_cores
        mkdir $CORE_DIR -p
        mkdir -p $DEST

        cd $CORE_DIR
        mkdir ../latest

        find ../../dist/qnx -name '*.so' -mmin -2160 -exec cp '{}' . \;

        find . -type f -name '*.so' -exec zip -j '{}'.zip '{}' \;
        find . -type f -name '*.so' -exec rm -v '{}' \;
        cp -v *.zip ../latest/

        cd $BOT
        cp -rfv packages/* $DEST
        cp -rfv $TMPDIR/log/* $LOGDEST
fi

