#!/bin/sh
export BASEDIR=/Users/buildbot
export RELEASE=$1
export VERSION=$2

echo BASEDIR: $BASEDIR
echo RELEASE: $RELEASE
echo VERSION: $VERSION

cd $BASEDIR/scripts
git pull
cd $BASEDIR

$BASEDIR/scripts/buildbot-master-osx
