#!/bin/bash

LOGDATE=`date +%Y-%m-%d`
BUILDBOT=vaporeon_linux
DEST=$BASEDIR/www/nightly/playstation/vita/
LOGDEST=$BASEDIR/www/log/
echo $LOGDATE $BUILDBOT
TMPDIR=$BASEDIR/.tmp/

mkdir -p $TMPDIR/log/$BUILDBOT/${LOGDATE}
echo Buildbot Summary | tee -a  $TMPDIR/log/${BUILDBOT}/${LOGDATE}.log

cd $BASEDIR
cd buildbot
WORKDIR=$PWD

### vita ###

# prepare build environment
BOT=$PWD/vita
cd $BOT
git pull
git clean -xdf

rm -rf packages
#build cores
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=6 ./libretro-buildbot-recipe.sh recipes/playstation/vita

# create packages and cleanup
if [ ! -f $TMPDIR/built-frontend -a ! -f $TMPDIR/built-cores ]; then
    echo "Nothing to do here!"
else
    echo BUILDBOT TASK: packaging cores
    CORE_DIR=$PWD/retroarch/pkg/vita
    mkdir -p $DEST
    command cd $CORE_DIR
    echo $
    ls -la

    7z a -mx9 $DEST/$(date +%F)_RetroArch.7z
fi

## end ###
rm $TMPDIR/built-cores $TMPDIR/built-frontend

