#!/bin/bash

LOGDATE=`date +%Y-%m-%d`
BUILDBOT=vaporeon_linux
DEST=$BASEDIR/www/nightly/linux/x86
LOGDEST=$BASEDIR/www/log
echo $LOGDATE $BUILDBOT
TMPDIR=$BASEDIR/.tmp/

mkdir -p $TMPDIR/log/$BUILDBOT/${LOGDATE}
echo Buildbot Summary | tee -a  $TMPDIR/log/${BUILDBOT}/${LOGDATE}.log

cd $BASEDIR
cd buildbot
WORKDIR=$PWD

### linux x86_64 ###

# prepare build environment
BOT=$PWD/linux_x86
cd $BOT
git pull
git clean -xdf

rm -rf packages
#build cores
TMPDIR=$TMPDIR LOGURL=$LOGURL SIG=$SIG BOT=$BUILDBOT JOBS=6 ./libretro-buildbot-recipe.sh recipes/linux/cores-linux-x86-generic

# create packages and cleanup
if [ ! -f $TMPDIR/built-frontend -a ! -f $TMPDIR/built-cores ]; then
    echo "Nothing to do here!"
else
        echo BUILDBOT TASK: packaging cores
        CORE_DIR=$PWD/packages/$(date +%F)_cores
        mkdir $CORE_DIR -p
        mkdir -p $DEST

        cd $CORE_DIR
        mkdir ../latest

        find ../../dist/unix -name '*.so' -mmin -2160 -exec cp '{}' . \;

        find . -type f -name '*.so' -exec zip -j '{}'.zip '{}' \;
        find . -type f -name '*.so' -exec rm -v '{}' \;
        cp -v *.zip ../latest/

        cd $BOT
        cp -rfv packages/* $DEST
        cp -rfv $TMPDIR/log/* $LOGDEST
fi

## end ###
rm $TMPDIR/built-cores $TMPDIR/built-frontend


