#!/bin/sh
export BASEDIR=/home/buildbot
export RELEASE="YES"
export VERSION="1.3.1"

cd $BASEDIR/scripts
git pull
cd $BASEDIR

screen -dmS buildbot $BASEDIR/scripts/buildbot-master
screen -list

if [ "${RELEASE}" = "YES" ]; then
   awk 'NR==3 {$0="export RELEASE="NO""} { print }' /home/buildbot/scripts/buildbot-master
   cd /home/buildbot/scripts/
   git commit -a -m"[buildbot] disable release build"
   git push
fi
