#!/bin/sh
export BASEDIR=/home/buildbot
export RELEASE="NO"
export VERSION="1.3.1"

cd $BASEDIR/scripts
git pull
cd $BASEDIR

screen -dmS buildbot $BASEDIR/scripts/buildbot-master
screen -list

if [ ! -f $BASEDIR/.tmp/buildbot.lock ]; then
   touch $BASEDIR/.tmp/buildbot.lock
   echo "buildbot not running"

else
   echo "buildbot already running"
   exit
fi

if [ "${RELEASE}" = "YES" ]; then
   cd /home/buildbot/scripts/
   git reset --hard
   sed -i 's/export RELEASE="NO"/export RELEASE="NO"/' /home/buildbot/scripts/buildbot-script
   git commit -a -m"[buildbot] disable release build"
   git push
fi
