#!/bin/bash
source $BASEDIR/scripts/buildbot.conf

if [ "${RELEASE}" = "YES" ]; then
   export FORCE_RETROARCH_BUILD=YES
else
   export FORCE_RETROARCH_BUILD=NO
fi

echo Enviroment Vars for OSX:
echo
echo LOGURL=$LOGURL
echo UPLOAD=$UPLOAD
echo BASEDIR=$BASEDIR
echo RELEASE=$RELEASE
echo VERSION=$VERSION
echo FORCE_RETROARCH_BUILD=$FORCE_RETROARCH_BUILD

if [ ! -f $BASEDIR/.tmp/buildbot.lock ]; then
   touch $BASEDIR/.tmp/buildbot.lock
else
   echo "buildbot already running"
   exit
fi

# Console targets first, usually smaller
$BASEDIR/scripts/buildbot-osx
$BASEDIR/scripts/buildbot-ios
$BASEDIR/scripts/buildbot-ios9

rm $BASEDIR/.tmp/buildbot.lock
rm $BASEDIR/.tmp/built*
rm -rfv $BASEDIR/.tmp/log

